import 'package:orpheus/data/model/nota.dart';

class Notas {
  static var lista = [
    Nota(
        id: 1,
        nome: "Dó",
        imagemRes: "do_clave_sol.png",
        posicaoEscalaSol: -2,
        cifra: "C",
        nivel: 0),
    Nota(
        id: 2,
        nome: "Ré",
        imagemRes: "re_clave_sol.png",
        posicaoEscalaSol: -1,
        cifra: "D",
        nivel: 0),
    Nota(
        id: 3,
        nome: "Mi",
        imagemRes: "mi_clave_sol.png",
        posicaoEscalaSol: 0,
        cifra: "E",
        nivel: 0),
    Nota(
        id: 4,
        nome: "Fá",
        imagemRes: "fa_clave_sol.png",
        posicaoEscalaSol: 1,
        cifra: "F",
        nivel: 0),
    Nota(
        id: 5,
        nome: "Sol",
        imagemRes: "sol_clave_sol.png",
        posicaoEscalaSol: 2,
        cifra: "G",
        nivel: 0),
    Nota(
        id: 6,
        nome: "Lá",
        imagemRes: "la_clave_sol.png",
        posicaoEscalaSol: 3,
        cifra: "A",
        nivel: 0),
    Nota(
        id: 7,
        nome: "Si",
        imagemRes: "si_clave_sol.png",
        posicaoEscalaSol: 4,
        cifra: "B",
        nivel: 0),
    Nota(
        id: 8,
        nome: "Dó Sustenido",
        imagemRes: "do_sustenido_clave_sol.png",
        posicaoEscalaSol: -2,
        cifra: "C#",
        nivel: 1),
    Nota(
        id: 9,
        nome: "Ré Sustenido",
        imagemRes: "re_sustenido_clave_sol.png",
        posicaoEscalaSol: -1,
        cifra: "D#",
        nivel: 1),
    Nota(
        id: 10,
        nome: "Fá Sustenido",
        imagemRes: "fa_sustenido_clave_sol.png",
        posicaoEscalaSol: 1,
        cifra: "F#",
        nivel: 1),
    Nota(
        id: 11,
        nome: "Sol Sustenido",
        imagemRes: "sol_sustenido_clave_sol.png",
        posicaoEscalaSol: 2,
        cifra: "G#",
        nivel: 1),
    Nota(
        id: 12,
        nome: "Lá Sustenido",
        imagemRes: "la_sustenido_clave_sol.png",
        posicaoEscalaSol: 3,
        cifra: "A#",
        nivel: 1),
    Nota(
        id: 13,
        nome: "Ré Bemol",
        imagemRes: "re_bemol_clave_sol.png",
        posicaoEscalaSol: -1,
        cifra: "Db",
        nivel: 1),
    Nota(
        id: 14,
        nome: "Mi Bemol",
        imagemRes: "mi_bemol_clave_sol.png",
        posicaoEscalaSol: 1,
        cifra: "Eb",
        nivel: 1),
    Nota(
        id: 15,
        nome: "Sol Bemol",
        imagemRes: "sol_bemol_clave_sol.png",
        posicaoEscalaSol: 2,
        cifra: "Gb",
        nivel: 1),
    Nota(
        id: 16,
        nome: "Lá Bemol",
        imagemRes: "la_bemol_clave_sol.png",
        posicaoEscalaSol: 2,
        cifra: "Ab",
        nivel: 1),
    Nota(
        id: 17,
        nome: "Si Bemol",
        imagemRes: "si_bemol_clave_sol.png",
        posicaoEscalaSol: 3,
        cifra: "Bb",
        nivel: 1),
  ];
}
